data<-read.table('household_power_consumption.txt', header=TRUE, sep=";")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
data<-subset(data, Date>="2007-02-01" & Date<="2007-02-02")
data$Global_active_power<-as.numeric(data$Global_active_power)
dateTime<-paste(data$Date, data$Time)
data<-cbind(data, dateTime)
data$dateTime<-as.POSIXct(data$dateTime)
par(mfrow=c(2,2), mar=c(4,4,2,1))
with(data, {
    plot(Global_active_power~dateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
    plot(Voltage~dateTime, type="l")
    plot(Sub_metering_1~dateTime, type="l",ylab="Energy sub meeting", xlab="")
    lines(Sub_metering_2~dateTime,col='red')
    lines(Sub_metering_3~dateTime,col='blue')
    legend('topright', col=c("black", "red", "blue"), lwd=c(1,1,1),legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
    plot(Global_reactive_power~dateTime, type="l")
})
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()
