par(mfrow=c(2,2), mar=c(4,4,2,1))
with(data, {
    plot(Global_active_power~dateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
    plot(Voltage~dateTime, type="l")
    plot(Sub_metering_1~dateTime, type="l",ylab="Energy sub meeting", xlab="")
    lines(Sub_metering_2~dateTime,col='red')
    lines(Sub_metering_3~dateTime,col='blue')
    legend('topright', col=c("black", "red", "blue"), lwd=c(1,1,1),legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
    plot(Global_reactive_power~dateTime, type="l")
})
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()
