data<-read.table('household_power_consumption.txt', header=TRUE, sep=";")
data$Date<-as.Date(data$Date, "%d/%m/%Y")
data<-subset(data, Date>="2007-02-01" & Date<="2007-02-02")
data$Global_active_power<-as.numeric(data$Global_active_power)
hist(data$Global_active_power, xlab="Global Active Power(kilowatts)", col="red", main="Global Active Power")
dev.copy(png,"plot1.png", width=480, height=480)
dev.off()
